### ISSUE TITLE
req.on('end', function() {}) never fires, middleware hangs

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-verifier-middleware#14]
With another body-parser above it (see https://github.com/alexa-js/alexa-app/issues/152) the middleware hangs. The middleware needs to read and process the entire request body in order for the validation to work, and express doesn't expose that on the request object directly. So it accumulates the whole data of the request before any processing happens. That doesn't explain why the request would hang.

**Comment by tejashah88** [comment]
Is this bug solved yet, or is there still a problem?

**Comment by dblock** [comment]
I believe it's not solved. The middleware part was addressed, ie. the way alexa-app uses alexa-verifier-middleware doesn't exhibit this behavior unless the user throws a bodyparser above it. When the user does, the middleware hangs.

**Comment by tejashah88** [comment]
I did some more testing and apparently, the body-parser seems to swallow up the entire request. This is because the req.on('data', function() {}) is never fired in the first place.

I dug through the `body-parser` source code, specifically [json.js](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L18), and I found that there are some debug statements that can be printed when you [set the environment variable of DEBUG](https://www.npmjs.com/package/debug#windows-note). I did that and this is the relevant output that I got:

![image](https://cloud.githubusercontent.com/assets/11187343/22721619/b6cfe764-ed66-11e6-8d1d-b8ab15b3bd22.png)

If you look at the middle, there is a debug line of interest: "read body". I traced it to [read.js](https://github.com/expressjs/body-parser/blob/master/lib/read.js#L74) and here's some interesting results:

![image](https://cloud.githubusercontent.com/assets/11187343/22721902/4b2f7d60-ed68-11e6-8eca-7d37993c5a42.png)

According to the few comments that I found, the `body-parser` seems to be reading the entire request body and then processing it.

**Comment by dblock** [comment]
Makes sense, this confirms the bug. There needs to be some code in the middleware that skips it when there's not going to be any data.

**Comment by tejashah88** [comment]
I disagree, as the purpose of this module would be defeated. If someone used a similar practice to [test_alexa_verifier_middleware_hangs.js](https://github.com/dblock/alexa-app/blob/test-hangs/test/test_alexa_verifier_middleware_hangs.js), he/she wouldn't really know why the verification fails  until we told him/her.

I'd say that the module should throw an error if the body is already processed and tell the user to change the code as necessary. An example would be:
```javascript
if (req._body) {
  return res.status(401).json({ status: 'failure', reason: 'The incoming body was already parsed! Are you sure that this module is loaded before any body-parser modules?' })
}
```

**Comment by dblock** [comment]
Yes you're right.
