### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by mreinstein** [alexa-js/alexa-verifier-middleware#25]
whoever added sinon and made recent commits related to tests, they're failing:

https://travis-ci.org/alexa-js/alexa-verifier-middleware/jobs/218540923

@tejashah88 @dblock I'm assuming these are test changes that you've commited. Please fix the tests.

**Comment by tejashah88** [comment]
@mreinstein Thanks for the notice.

What's interesting to note is that a couple of months ago, the tests were passing, and only recently, I re-ran the tests again, and not only are the current tests failing but the past tests are failing as well.

![image](https://user-images.githubusercontent.com/11187343/29535189-d6d41954-866d-11e7-95ff-413ccaffea68.png)

Looking more into the current tests, we have two problems.

1. For older versions of node, (> 4.0), the dependencies are breaking the tests due to new language features such as ['const' not allowed in strict mode](https://travis-ci.org/alexa-js/alexa-verifier-middleware/jobs/218540910#L260).
2. For the newer versions, the errors that are supposed to be caught should return a `401` error, but they return a `200` instead, along with a `SyntaxError` saying it's unable to parse the JSON string.

![image](https://user-images.githubusercontent.com/11187343/29535447-b2cfba30-866e-11e7-80b6-2bcc5b8d3c74.png)

This error affects all builds until #17, and weird enough, the tests were passing.
![image](https://user-images.githubusercontent.com/11187343/29535672-a1ac4664-866f-11e7-8db2-21bd3881d806.png)

I'm kind of stumped since a test shouldn't just pass, then fail after some time. without any change, but I'll keep looking into it.

**Comment by mreinstein** [comment]
> I'm kind of stumped since a test shouldn't just pass, then fail after some time. 

I suspect this is because one of the dependencies of this module had an API breaking change but failed to update their major version number.

**Comment by mreinstein** [comment]
imo there is too much test setup magic in the tests. removing `sinon`, `node-mocks-http` and writing simple assertions would likely fix all of these problems.

**Comment by mreinstein** [comment]
another issue: `alexa-verifier@0.3.5` removed support for node 0.10 and 0.12. Might want to consider removing node 0.10 and 0.12 support from this module, as it's no longer supported by nodejs and considered super, super, super old.

**Comment by mreinstein** [comment]
The remaining failures are due to the way that the tests are setup. As of `alexa-verifier@0.3.4` and newer, the callback is always asynchronous.  see: https://github.com/mreinstein/alexa-verifier/commit/f5a7a2d43a9b4f6e3222dfb0e8d39aa4df75e73e

the tests seem set up to expect a synchronous handler

**Comment by mreinstein** [comment]
ok after pinning `alexa-verifier` to 0.3.3, the tests still fail, but now they fail due to the dev modules relying on node v4 and up. I'm going to remove the tests for node < 4 from travis.
